src/widgets/ot_popup.eliom
src/widgets/ot_popup.eliomi

- tabindex cycles only on popup elements
- first input element of the form receives focus

better UI behaviour for forms in a popup

---

src/widgets/ot_popup.eliom
src/widgets/ot_popup.eliomi

if ?setup_popup parameter is true Ot_popup.popup will scan its content for a form element and run Ot_popup.setup_form_auto on it.
Ot_popup.setup_form_auto scans an element for inputs and buttons and runs Ot_popup.setup_form on them.

automated popup form setup

---

css/ot_buttons.css
src/widgets/ot_buttons.eliom

this is a workaround for unpredictable hover behaviour on iOS

dropdown button creates a background and a container

---

src/widgets/ot_carousel.eliom
src/widgets/ot_drawer.eliom
src/widgets/ot_picture_uploader.eliom
src/widgets/ot_swipe.eliom
src/widgets/ot_time_picker.eliom

modified:   src/widgets/ot_carousel.eliom
modified:   src/widgets/ot_drawer.eliom
modified:   src/widgets/ot_picture_uploader.eliom
modified:   src/widgets/ot_swipe.eliom
modified:   src/widgets/ot_time_picker.eliom

add touchcancel handlers

---

src/widgets/ot_carousel.eliom
src/widgets/ot_drawer.eliom

modified:   src/widgets/ot_carousel.eliom
modified:   src/widgets/ot_drawer.eliom

debugging (Lwt.pick+Lwt_js_events)

---

src/widgets/ot_social_meta.eliom
src/widgets/ot_social_meta.eliomi

Extract meta information used by twitter and facebook.

Added Ot_social_meta module.

---

src/widgets/ot_carousel.eliom

modified:   src/widgets/ot_carousel.eliom

trying to fix Ot_carousel.ribbon

---

src/widgets/ot_sticky.eliom
src/widgets/ot_sticky.eliomi

It's a "bad" fix based on a delay, because some things seem to happen too early. I can't figure out how to do it without a delay right now.

fix incorrect initialisation of the left sticky pane

---

src/widgets/ot_lib.eliomi
src/widgets/ot_popup.eliom
src/widgets/ot_popup.eliomi
src/widgets/ot_spinner.eliom
src/widgets/ot_spinner.eliomi
src/widgets/ot_style.eliom
src/widgets/ot_style.eliomi

react to dynamic changes
disable tabbing of background elements
deal with hidden and disabled form elements

more automation in popup forms

---

src/widgets/ot_sticky.eliom

previously: only on height change

Ot_sticky: recompute sizes also on window width change

---

src/widgets/ot_carousel.eliom
src/widgets/ot_drawer.eliom
src/widgets/ot_lib.eliom
src/widgets/ot_popup.eliom
src/widgets/ot_sticky.eliom

Eliom_client.onunload API change

---

src/widgets/ot_style.eliom
src/widgets/ot_style.eliomi

I think this sum type must be integrated directly in the jsoo lib, as other CSS styles values.

Old TODO: Add sum type for the display value.

---

src/widgets/ot_drawer.eliom
src/widgets/ot_swipe.eliom

Remove some warnings.

---

src/widgets/ot_icons.eliom

- Add some comments to explain

- Remove fa icon (Font Awesome dependency).

---

css/ot_carousel.css
src/widgets/ot_carousel.eliom

(because it causes some troubles)

Carousel: now using translate instead of translate3d

---

css/ot_carousel.css
src/widgets/ot_carousel.eliom

Carousel: now using translate instead of translate3d (because it causes some troubles)

---

src/widgets/ot_drawer.eliom

modified:   src/widgets/ot_drawer.eliom
@balat I'm not sure it's what we should do...

fix: avoid (failwith "bind_touch")

---

src/widgets/ot_sticky.eliomi

After having botched a conflict resolution.

removed obsolete documentation for Ot_sticky

---

css/ot_popup.css

There is already the icon from `Ot_icons`.

Remove double close icon.

---

css/ot_picture_uploader.css

No border when no file in picture uploader form

---

src/widgets/ot_buttons.eliom
src/widgets/ot_calendar.eliom
src/widgets/ot_carousel.eliom
src/widgets/ot_drawer.eliom
src/widgets/ot_nodeready.eliom
src/widgets/ot_picture_uploader.eliom
src/widgets/ot_popup.eliom
src/widgets/ot_spinner.eliom
src/widgets/ot_sticky.eliom
src/widgets/ot_swipe.eliom

In the spirit of https://github.com/ocsigen/ocsigen-start/pull/441

Pre allocated lwt thread

---

src/widgets/ot_carousel.eliom

- before: starting swiping without any actual move would make the carousel enter a wrong state
- after: avoid waiting for any transitionend when no transition is happening
modified:   src/widgets/ot_carousel.eliom
with great help from @vouillon

fix: carousel scrolling issue on iOS webkit

---

src/widgets/ot_carousel.eliom
src/widgets/ot_carousel.eliomi

pull also: https://github.com/besport/bs/pull/2156

Lazy carousel

---

src/widgets/ot_carousel.eliom

... for the initially selected page

lazy carousel: client side: asynchronous content generation

---

src/widgets/ot_carousel.eliom
src/widgets/ot_carousel.eliomi

i.e. a position signal that is triggered after the tab switch animation

carousel: return a pos_post signal

---

src/widgets/ot_carousel.eliom

resolves the issue about endlessly turning spinners

lazy carousel: display error message in HTML instead of JS console

---

css/ot_page_transition.css
ocsigen-toolkit.install
src/widgets/ot_page_transition.eliom
src/widgets/ot_page_transition.eliomi

I add a new widget that helps realize page transition with screenshots.

Add ot_page_transition widget

---

src/widgets/ot_page_transition.eliom

eliom:6bf371b1c15967d486584054f1e3510e14e04bcf

compatibility with Eliom

---

src/widgets/ot_tip.eliom
src/widgets/ot_tip.eliomi

It is centered if this fits on screen. Otherwise, its right or left side (whichever fits best) is at the center of the origin.

Ot_tip: change positioning

---

css/ot_color_picker.css
doc/indexdoc.client
doc/manual-wiki/intro.wiki
src/widgets/ot_color_picker.eliom
src/widgets/ot_color_picker.eliomi

This is based on the PR by @ilankri , using DOM grids and reactive programming instead of canvases.

Color picker

---

doc/manual-wiki/intro.wiki

This prepares the migration to `html_of_wiki`...

Convert site links to wiki links

---

src/widgets/ot_tip.eliom
src/widgets/ot_tip.eliomi

Ot_tip: restore the optional 'side' argument

---

opam
src/widgets/ot_pulltorefresh.eliom
src/widgets/ot_pulltorefresh.eliomi

Used a square root function to compute drag distance, rather than linear translation.
Makes the container move a little better.
Added a public parameter to change the scaling of the curve

[pulltorefresh] smoother dragging motion + application-only option

---

src/widgets/ot_pulltorefresh.eliom

In a situation where an element is horizontally scrollable *and* inside a refreshable container, we need to let them scroll.

[pulltorefresh] don't do anything when user scrolls horizontally

---

opam
src/widgets/ot_carousel.eliom

For example when we want some space between pages

Carousel: make it possible to use it when less than 1 page is visible

---

CHANGES
css/ot_tongue.css
ocsigen-toolkit.install
opam
src/widgets/ot_tongue.eliom
src/widgets/ot_tongue.eliomi

Add widget ot_tongue

---

.github/workflows/build.yml
Makefile
Makefile.options
opam
src/widgets/ot_calendar.eliom
src/widgets/ot_carousel.eliom
src/widgets/ot_carousel.eliomi
src/widgets/ot_color_picker.eliom
src/widgets/ot_drawer.eliom
src/widgets/ot_popup.eliom
src/widgets/ot_range.eliom
src/widgets/ot_spinner.eliom
src/widgets/ot_swipe.eliom
src/widgets/ot_time_picker.eliom
src/widgets/ot_toggle.eliom

This induces the removal of a number of unused functions and parameters.

[cosmetics] render many compiler warnings fatal

---

src/widgets/ot_calendar.eliom
src/widgets/ot_calendar.eliomi
src/widgets/ot_carousel.eliom
src/widgets/ot_color_picker.eliom
src/widgets/ot_picture_uploader.eliom
src/widgets/ot_size.eliom
src/widgets/ot_spinner.eliom
src/widgets/ot_spinner.eliomi
src/widgets/ot_sticky.eliom
src/widgets/ot_time_picker.eliom
src/widgets/ot_toggle.eliom
src/widgets/ot_tongue.eliom

Now that weak references are properly implemented by Js_of_ocaml, we need to make sure that signals and events do not get garbage collected too early.

React fixes
