- Makefile
- Makefile.options
- src/widgets/ot_calendar.eliom
- src/widgets/ot_calendar.eliomi
- src/widgets/ot_range.eliom
- src/widgets/ot_range.eliomi
- src/widgets/ot_time_picker.eliom
- src/widgets/ot_time_picker.eliomi
- src/widgets/ot_toggle.eliom
- src/widgets/ot_toggle.eliomi
I think it is a good idea to start converting some of our own stuff to PPX, to stress the extension, and also to prepare for a PPX-centric future. Let's start with `ocsigen-toolkit`.
The conversion happened in a semi-automated fashion using an [extended `camlp4-to-ppx`](https://github.com/vasilisp/camlp4-to-ppx) (via the composition of the `lwt`, `eliom`, and `deriving` branches)
@Drup, can you take a look at the style introduced by cafdac3256de2c33de6f4dad80ea7c5e16048708? I am using `[%%shared.start]` to set up the default, and `let%client`, `let%server` to override as necessary. I like this, and it seems to work, but please double-check.
I would like to merge this soon so that subsequent work (e.g., for #2) is PPX-only :).
The library will still be usable from Camlp4 projects, with no …
> Convert to PPX

- src/widgets/ot_drawer.eliom
- src/widgets/ot_drawer.eliomi
- src/widgets/ot_popup.eliom
- src/widgets/ot_popup.eliomi
- notify html-element of popup/drawer opening
- workaround for weird scroll behaviour in iOS when preventing the body to scroll
> required for body scroll block on drawer/popup opening

- css/ot_sticky.css
- opam/opam
- src/widgets/ot_sticky.eliom
- src/widgets/ot_sticky.eliomi
- src/widgets/ot_style.eliom
works well now, as far as I can see.
Main change is that instead of "deep cloning" the element its children are moved back and forth between the fixed and the inline element. Otherwise all the javascript code is broken.
> reworked position:sticky-polyfill

- src/widgets/ot_lib.eliom
- src/widgets/ot_lib.eliomi
- src/widgets/ot_spinner.eliom
- src/widgets/ot_sticky.eliom
- src/widgets/ot_sticky.eliomi
fixes broken sticky tab when page generated on client-side
> fix initialisation of position:sticky-polyfill (also pull bs)

- css/ot_carousel.css
On all the browsers I tried it prevented the bullets to be displayed.
> ot_carousel.css : removed display attribute for bullet-nav-item class

- Makefile
OCaml now issues a warning when they are missing
> Install cmx files as well

- src/widgets/ot_carousel.eliom
- src/widgets/ot_carousel.eliomi
We can now give some Html content to the [bullets] function to fill the generated bullets.
> ot_carousel bullets function extended

- src/widgets/ot_picture_uploader.eliom
- src/widgets/ot_style.eliom
`string_of_float 49.` is `"49."`, which is not a valid CSS number.
> Do not use string_of_float to generate CSS numbers.

- src/widgets/ot_swipe.eliom
cause: iOS 10 silently doesn't support creation of Touch objects.
solution: when a Touch object is badly created, do fallback to the other solution.
modified:   src/widgets/ot_swipe.eliom
> fix: swiping on iOS 10

- src/widgets/ot_swipe.eliom
cause: iOS 10 silently doesn't support creation of Touch objects.
solution: when a Touch object is badly created, do fallback to the other solution.
modified:   src/widgets/ot_swipe.eliom
> fix: swiping on iOS 10 (on branch bs)

- src/widgets/ot_picture_uploader.eliom
- src/widgets/ot_picture_uploader.eliomi
We are planning to remove the client-side service creation API from Eliom. This will enforce using injections for services, and thus lead to a less error-prone programming style.
There is already an Eliom branch for that (`service-server-only`).
The first step is to remove client-side service creation from the reverse dependencies of Eliom. It will be smoother if we merge the associated PRs before the upcoming Eliom one.
> Ot_picture_uploader.mk_service becomes server-only

- Makefile
With this rule, we can clean the generated documentation with the Makefile and not manually.
> Add a rule 'doc-clean'

- css/ot_carousel.css
- src/widgets/ot_carousel.eliom
Add `will-change` hints and use `transform` to translate the cursor.
We now assume that the cursor has no margin, so some style adjustments may be needed for drawing the cursor.
> Carousel performance improvements

- css/ot_drawer.css
- css/ot_popup.css
- src/widgets/ot_drawer.eliom
- src/widgets/ot_drawer.eliomi
- src/widgets/ot_popup.eliom
- src/widgets/ot_popup.eliomi
Now setting position:fixed and manually change top property
> Ot_popup/drawer: improve hack for preventing background scroll when a popup/drawer is open on mobile devices

- src/widgets/ot_nodeready.eliom
We stop watching an element after two page changes.
> Ot_nodeready: do not watch elements forever, to avoid memory leaks

- opam
- src/widgets/ot_calendar.eliom
- src/widgets/ot_carousel.eliom
- src/widgets/ot_carousel.eliomi
- src/widgets/ot_drawer.eliom
- src/widgets/ot_form.eliom
- src/widgets/ot_form.eliomi
- src/widgets/ot_lib.eliomi
- src/widgets/ot_nodeready.eliomi
- src/widgets/ot_noderesize.eliom
- src/widgets/ot_noderesize.eliomi
- src/widgets/ot_page_transition.eliom
- src/widgets/ot_picture_uploader.eliom
- src/widgets/ot_picture_uploader.eliomi
- src/widgets/ot_range.eliom
- src/widgets/ot_size.eliom
- src/widgets/ot_size.eliomi
- src/widgets/ot_spinner.eliom
- src/widgets/ot_style.eliom
- src/widgets/ot_style.eliomi
- src/widgets/ot_swipe.eliom
- src/widgets/ot_swipe.eliomi
- src/widgets/ot_time_picker.eliom
- src/widgets/ot_tip.eliom
- src/widgets/ot_tip.eliomi
- src/widgets/ot_toggle.eliom
reinstate "ot-drawer-open" on html element when returning to page
> Ot_drawer: compatibility with DOM caching

- ocsigen-toolkit.install
Make that ot_color_picker.css is put into the folder .opam/<version>/share/ocsigen-toolkit/css when ocsigen-toolkit is installed by opam.
> fix : add a rule to put ot_color_picker.css into share folder

- src/widgets/ot_pulltorefresh.eliom
The last PR introduced an option to make the wrapping happen only on mobile apps.
In this case, the browser version lost the given attributes (`~a`)
We want to keep those.
> [pulltorefresh] don't lose wrapper attributes on browser

- src/widgets/ot_popup.eliom
- src/widgets/ot_popup.eliomi
This parameter exist to be able to disable scroll hacks on popups.
This is useful to have full control on what happens when any popup is closed.
> Toggle popups scroll hack parameter

- Makefile.options
See [ ocsigen-toolkit doesn't compile after js_of_ocaml.3.6.0 update #196 ](https://github.com/ocsigen/ocsigen-toolkit/issues/196)
> fix pkg set to js_of_ocaml-ppx_deriving_json #1005

- css/ot_page_transition.css
- opam
- src/widgets/ot_page_transition.eliom
Request handling makes the animation stutter, so we disable for the duration of the page transition animation. Also completeley reworked the animation.
Everything works fine except for some flickering on iOS.
> Ot_page_transition: completely rework animation

- css/ot_datetime.css
- opam
- src/widgets/ot_calendar.eliom
- src/widgets/ot_calendar.eliomi
The focus here is on `src/widgets/ot_calendar.eliom` and `src/widgets/ot_calendar.eliomi`  files.
* Possibility to **change the month** via a selector
* Possibility to **change the year** via a selector as well
* When there is a period restriction the days that are not in the period are displayed differently and are not clickable anymore.
* **Period restriction type** added in order to have a customizable calendar.
* **Refactoring** of the way the handlers were written in the file in order to avoid redundancies
* **Selectors** added for months and years
* **Handlers** added for months and years thanks to the (very) helpful `React` module.
In order to be able to test the changes, a very simple way to do is : 
* Clone this repository on your computer and pin (via opam : *opam pin add --kind …
> [ot-calendar] Remodelling of the calendar toolkit

- opam
- src/widgets/ot_tip.eliom
Since, by mistake, the previous PR () did not change the version,
the version which would have been at 3.0.0 is therefore now at 3.0.1
> [ot-tip] Use document client width instead of window inner width

- css/ot_tongue.css
We should use vh instead of % since in css attributes 'translate[Y|X]' percentage are based on the element's dimensions and not on the viewport's dimensions
> [ot-tongue-css] vh instead of % for initial translateY in Bottom case

- .github/workflows/build.yml
To avoid the warning about deprecated Node.js 12 actions.
> [ci] Use the latest version of `actions/checkout`

- Makefile.options
- src/widgets/ot_calendar.eliom
- src/widgets/ot_carousel.eliom
- src/widgets/ot_drawer.eliom
- src/widgets/ot_lib.eliom
- src/widgets/ot_page_transition.eliom
- src/widgets/ot_picture_uploader.eliom
- src/widgets/ot_popup.eliom
- src/widgets/ot_pulltorefresh.eliom
- src/widgets/ot_spinner.eliom
- src/widgets/ot_sticky.eliom
- src/widgets/ot_swipe.eliom
- src/widgets/ot_tongue.eliom
This PR proposes to get rid of the `%lwt` syntax from `lwt_ppx` in favor of the
`Lwt_syntax`.
This is join work with @Julow (who wrote the tool making the automatic changes)
Most of the changes has been done automatically using the prototype tool
[here](https://github.com/Julow/lwt_ppx_to_let_syntax). This is the reason why
the PR is one big commit.
The `open Lwt.Syntax`s were not always placed at the right places as the syntax
is not necessarily used both on the client and server side in each file. This
has been fixed by hand.
I haven't understood the setup to run ocamlformat: it needs more arguments than
present in the `.ocamlformat` file and I haven't figure out all of them yet.
Nevertheless, this is also fixed by hand and the diff is minimal.
This is a first step toward moving from …
> Remove `lwt_ppx` dependency
